// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _016_Exam;

#nullable disable

namespace _016_Exam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318162224_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscSale", b =>
                {
                    b.Property<int>("DiscsId")
                        .HasColumnType("int");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("DiscsId", "SalesId");

                    b.HasIndex("SalesId");

                    b.ToTable("DiscSale");
                });

            modelBuilder.Entity("_016_Exam.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("GanreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Shelved")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<int>("SongsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GanreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Discs", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount >= 0");

                            t.HasCheckConstraint("Cost", "Cost >= 0");

                            t.HasCheckConstraint("Price", "Price > Cost");

                            t.HasCheckConstraint("Shelved", "Shelved >= 0");

                            t.HasCheckConstraint("Sold", "Sold >= 0");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Ganre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ganres");
                });

            modelBuilder.Entity("_016_Exam.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("_016_Exam.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<double>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<double>("PriceForOne")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount > 0")
                                .HasName("Amount1");

                            t.HasCheckConstraint("FinalPrice", "FinalPrice >= PriceForOne");

                            t.HasCheckConstraint("PriceForOne", "PriceForOne > 0");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Sale", t =>
                        {
                            t.HasCheckConstraint("Discount", "Discount > 0 AND Discount < 100");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.ShelvedDiscs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("UserId");

                    b.ToTable("ShelvedDiscs", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount >= 0")
                                .HasName("Amount2");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscSale", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", null)
                        .WithMany()
                        .HasForeignKey("DiscsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Sale", null)
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.HasOne("_016_Exam.Models.Author", "Author")
                        .WithMany("Discs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Ganre", "Ganre")
                        .WithMany("Discs")
                        .HasForeignKey("GanreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Publisher", "Publisher")
                        .WithMany("Discs")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ganre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("_016_Exam.Models.Purchase", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", "Disc")
                        .WithMany("Purchases")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_016_Exam.Models.ShelvedDiscs", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", "Disc")
                        .WithMany("ShelvedDiscs")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.User", "User")
                        .WithMany("ShelvedDiscs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_016_Exam.Models.Author", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("ShelvedDiscs");
                });

            modelBuilder.Entity("_016_Exam.Models.Ganre", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.Publisher", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.User", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("ShelvedDiscs");
                });
#pragma warning restore 612, 618
        }
    }
}
