// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _016_Exam;

#nullable disable

namespace _016_Exam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscSale", b =>
                {
                    b.Property<int>("DiscsId")
                        .HasColumnType("int");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("DiscsId", "SalesId");

                    b.HasIndex("SalesId");

                    b.ToTable("DiscSale");
                });

            modelBuilder.Entity("_016_Exam.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Emma",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Michael",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Olivia",
                            Surname = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            Name = "William",
                            Surname = "Miller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sophia",
                            Surname = "Wilson"
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("GanreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Shelved")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<int>("SongsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GanreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Discs", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount >= 0");

                            t.HasCheckConstraint("Cost", "Cost >= 0");

                            t.HasCheckConstraint("Price", "Price > Cost");

                            t.HasCheckConstraint("Shelved", "Shelved >= 0");

                            t.HasCheckConstraint("Sold", "Sold >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50,
                            AuthorId = 1,
                            Cost = 5.2000000000000002,
                            GanreId = 1,
                            Name = "Rock Legends",
                            Price = 15.9,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(2010, 5, 12),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 12
                        },
                        new
                        {
                            Id = 2,
                            Amount = 80,
                            AuthorId = 2,
                            Cost = 4.0,
                            GanreId = 2,
                            Name = "Pop Hits",
                            Price = 12.5,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2015, 3, 8),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 10
                        },
                        new
                        {
                            Id = 3,
                            Amount = 40,
                            AuthorId = 3,
                            Cost = 6.5,
                            GanreId = 3,
                            Name = "Jazz Night",
                            Price = 18.0,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2008, 11, 21),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 8
                        },
                        new
                        {
                            Id = 4,
                            Amount = 70,
                            AuthorId = 4,
                            Cost = 3.7999999999999998,
                            GanreId = 4,
                            Name = "Hip-Hop Beats",
                            Price = 11.0,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2020, 7, 15),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 14
                        },
                        new
                        {
                            Id = 5,
                            Amount = 30,
                            AuthorId = 5,
                            Cost = 7.5,
                            GanreId = 5,
                            Name = "Classic Collection",
                            Price = 20.0,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2000, 1, 1),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 20
                        },
                        new
                        {
                            Id = 6,
                            Amount = 55,
                            AuthorId = 6,
                            Cost = 5.0,
                            GanreId = 1,
                            Name = "Rock Arena",
                            Price = 14.0,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(2012, 6, 18),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 11
                        },
                        new
                        {
                            Id = 7,
                            Amount = 75,
                            AuthorId = 1,
                            Cost = 4.2000000000000002,
                            GanreId = 2,
                            Name = "Pop Dreams",
                            Price = 13.0,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2016, 4, 10),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 13
                        },
                        new
                        {
                            Id = 8,
                            Amount = 35,
                            AuthorId = 2,
                            Cost = 6.0,
                            GanreId = 3,
                            Name = "Smooth Jazz",
                            Price = 17.5,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2009, 2, 25),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 7
                        },
                        new
                        {
                            Id = 9,
                            Amount = 90,
                            AuthorId = 3,
                            Cost = 3.5,
                            GanreId = 4,
                            Name = "Street Beats",
                            Price = 10.5,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(2021, 8, 5),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 15
                        },
                        new
                        {
                            Id = 10,
                            Amount = 20,
                            AuthorId = 4,
                            Cost = 8.0,
                            GanreId = 5,
                            Name = "Symphony Best",
                            Price = 22.0,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(1995, 12, 12),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 25
                        },
                        new
                        {
                            Id = 11,
                            Amount = 45,
                            AuthorId = 5,
                            Cost = 5.0999999999999996,
                            GanreId = 1,
                            Name = "Rock Energy",
                            Price = 15.0,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2011, 3, 3),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 12
                        },
                        new
                        {
                            Id = 12,
                            Amount = 85,
                            AuthorId = 6,
                            Cost = 4.4000000000000004,
                            GanreId = 2,
                            Name = "Pop Star",
                            Price = 13.9,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(2017, 9, 9),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 11
                        },
                        new
                        {
                            Id = 13,
                            Amount = 25,
                            AuthorId = 1,
                            Cost = 6.7999999999999998,
                            GanreId = 3,
                            Name = "Jazz Classics",
                            Price = 19.0,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2007, 6, 14),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 9
                        },
                        new
                        {
                            Id = 14,
                            Amount = 95,
                            AuthorId = 2,
                            Cost = 3.8999999999999999,
                            GanreId = 4,
                            Name = "Rap Kings",
                            Price = 12.0,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2022, 2, 2),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 16
                        },
                        new
                        {
                            Id = 15,
                            Amount = 15,
                            AuthorId = 3,
                            Cost = 7.7999999999999998,
                            GanreId = 5,
                            Name = "Orchestra Gold",
                            Price = 21.5,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(1998, 10, 30),
                            Shelved = 0,
                            Sold = 0,
                            SongsCount = 18
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Ganre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ganres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Classical"
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Universal Music"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sony Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warner Music"
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<double>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<double>("PriceForOne")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount > 0")
                                .HasName("Amount1");

                            t.HasCheckConstraint("FinalPrice", "FinalPrice >= PriceForOne");

                            t.HasCheckConstraint("PriceForOne", "PriceForOne > 0");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Sales", t =>
                        {
                            t.HasCheckConstraint("Discount", "Discount > 0 AND Discount < 100");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.ShelvedDiscs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("UserId");

                    b.ToTable("ShelvedDiscs", t =>
                        {
                            t.HasCheckConstraint("Amount", "Amount >= 0")
                                .HasName("Amount2");
                        });
                });

            modelBuilder.Entity("_016_Exam.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("PermissionLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscSale", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", null)
                        .WithMany()
                        .HasForeignKey("DiscsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Sale", null)
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.HasOne("_016_Exam.Models.Author", "Author")
                        .WithMany("Discs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Ganre", "Ganre")
                        .WithMany("Discs")
                        .HasForeignKey("GanreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.Publisher", "Publisher")
                        .WithMany("Discs")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ganre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("_016_Exam.Models.Purchase", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", "Disc")
                        .WithMany("Purchases")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_016_Exam.Models.ShelvedDiscs", b =>
                {
                    b.HasOne("_016_Exam.Models.Disc", "Disc")
                        .WithMany("ShelvedDiscs")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_016_Exam.Models.User", "User")
                        .WithMany("ShelvedDiscs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_016_Exam.Models.Author", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.Disc", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("ShelvedDiscs");
                });

            modelBuilder.Entity("_016_Exam.Models.Ganre", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.Publisher", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("_016_Exam.Models.User", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("ShelvedDiscs");
                });
#pragma warning restore 612, 618
        }
    }
}
