// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _012_BookAuthors;

#nullable disable

namespace _012_BookAuthors.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAuthors", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 4
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 5
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 6
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 8
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 9
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 10
                        },
                        new
                        {
                            AuthorsId = 11,
                            BooksId = 11
                        },
                        new
                        {
                            AuthorsId = 12,
                            BooksId = 12
                        },
                        new
                        {
                            AuthorsId = 13,
                            BooksId = 13
                        },
                        new
                        {
                            AuthorsId = 13,
                            BooksId = 14
                        },
                        new
                        {
                            AuthorsId = 14,
                            BooksId = 14
                        },
                        new
                        {
                            AuthorsId = 14,
                            BooksId = 15
                        },
                        new
                        {
                            AuthorsId = 15,
                            BooksId = 16
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 17
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 18
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 19
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 20
                        });
                });

            modelBuilder.Entity("_012_BookAuthors.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Michael",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "David",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "James",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Robert",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "William",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Richard",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Joseph",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Thomas",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Charles",
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Daniel",
                            LastName = "Hernandez"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Matthew",
                            LastName = "Lopez"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Anthony",
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Mark",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Donald",
                            LastName = "Anderson"
                        });
                });

            modelBuilder.Entity("_012_BookAuthors.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books", t =>
                        {
                            t.HasCheckConstraint("Pages", "Pages >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# Fundamentals",
                            Pages = 350,
                            Price = 35.5f,
                            PublisherId = 9
                        },
                        new
                        {
                            Id = 2,
                            Name = ".NET Deep Dive",
                            Pages = 420,
                            Price = 40f,
                            PublisherId = 9
                        },
                        new
                        {
                            Id = 3,
                            Name = "Entity Framework Guide",
                            Pages = 300,
                            Price = 32.2f,
                            PublisherId = 8
                        },
                        new
                        {
                            Id = 4,
                            Name = "ASP.NET Core Web",
                            Pages = 500,
                            Price = 45f,
                            PublisherId = 8
                        },
                        new
                        {
                            Id = 5,
                            Name = "LINQ in Action",
                            Pages = 280,
                            Price = 28.9f,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 6,
                            Name = "Algorithms Basics",
                            Pages = 610,
                            Price = 55.5f,
                            PublisherId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Data Structures",
                            Pages = 540,
                            Price = 50f,
                            PublisherId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Clean Code Guide",
                            Pages = 450,
                            Price = 42.3f,
                            PublisherId = 10
                        },
                        new
                        {
                            Id = 9,
                            Name = "Design Patterns",
                            Pages = 395,
                            Price = 39.9f,
                            PublisherId = 10
                        },
                        new
                        {
                            Id = 10,
                            Name = "Microservices Architecture",
                            Pages = 370,
                            Price = 37.5f,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "Docker for Developers",
                            Pages = 260,
                            Price = 29.5f,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kubernetes Essentials",
                            Pages = 330,
                            Price = 34f,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 13,
                            Name = "AI Basics",
                            Pages = 410,
                            Price = 44.5f,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Machine Learning Intro",
                            Pages = 390,
                            Price = 41f,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Deep Learning Guide",
                            Pages = 520,
                            Price = 52f,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "Python for Data Science",
                            Pages = 360,
                            Price = 36f,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Statistics Essentials",
                            Pages = 300,
                            Price = 31f,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Game Development Basics",
                            Pages = 480,
                            Price = 43.7f,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Computer Graphics",
                            Pages = 510,
                            Price = 49.5f,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "Operating Systems",
                            Pages = 620,
                            Price = 58.9f,
                            PublisherId = 1
                        });
                });

            modelBuilder.Entity("_012_BookAuthors.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Penguin Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HarperCollins"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oxford Press"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cambridge Press"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Springer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Packt Publishing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Manning Publications"
                        },
                        new
                        {
                            Id = 9,
                            Name = "O’Reilly Media"
                        },
                        new
                        {
                            Id = 10,
                            Name = "No Starch Press"
                        });
                });

            modelBuilder.Entity("BookAuthors", b =>
                {
                    b.HasOne("_012_BookAuthors.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_012_BookAuthors.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_012_BookAuthors.Book", b =>
                {
                    b.HasOne("_012_BookAuthors.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("_012_BookAuthors.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
