// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _009_Films;

#nullable disable

namespace _009_Films.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorFilm", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("FilmsId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "FilmsId");

                    b.HasIndex("FilmsId");

                    b.ToTable("ActorFilm");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            FilmsId = 1
                        },
                        new
                        {
                            ActorsId = 4,
                            FilmsId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            FilmsId = 2
                        },
                        new
                        {
                            ActorsId = 3,
                            FilmsId = 3
                        });
                });

            modelBuilder.Entity("_009_Films.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leonardo",
                            Surname = "DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sam",
                            Surname = "Neill"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tom",
                            Surname = "Cruise"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Joseph",
                            Surname = "Gordon-Levitt"
                        });
                });

            modelBuilder.Entity("_009_Films.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudioId = 1,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            StudioId = 2,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 3,
                            StudioId = 3,
                            Title = "Top Gun"
                        });
                });

            modelBuilder.Entity("_009_Films.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warner Bros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Universal Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paramount Pictures"
                        });
                });

            modelBuilder.Entity("ActorFilm", b =>
                {
                    b.HasOne("_009_Films.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_009_Films.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_009_Films.Film", b =>
                {
                    b.HasOne("_009_Films.Studio", "Studio")
                        .WithMany("Films")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("_009_Films.Studio", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
